#include "MotionSynthesis/MotionPrimitive.hpp"
#include "MotionSynthesis/Skeleton.hpp"
#include "MotionSynthesis/MotionDatabase.hpp"
#include "MotionSynthesis/MotionBlender.hpp"
#include "MotionSynthesis/MotionPrimitiveBlender.hpp"
#include "MotionSynthesis/MotionDatabaseBuilder.hpp"
