#ifndef __FVF_BUMPVERTEX_H__
#define __FVF_BUMPVERTEX_H__

// BUMPVERTEX
//  for objects that use normal maps

#include <d3dx9.h>
#include "../TextureCoord.hpp"


namespace amorphous
{

// FVF format - possible for this bump vertex?
//#define D3DFVF_BUMPVERTEX (D3DFVF_XYZ|D3DFVF_NORMAL|D3DFVF_DIFFUSE|D3DFVF_TEX2)


// vertex decleration
const D3DVERTEXELEMENT9 BUMPVERTEX_DECLARATION[7] =
{
    { 0, 0,  D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION,0 }, // 12
    { 0, 12, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL,	0 }, // 12
	{ 0, 24, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TANGENT,	0 }, // 12
	{ 0, 36, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_BINORMAL,0 }, // 12
	{ 0, 48, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR,	0 }, // 4
    { 0, 52, D3DDECLTYPE_FLOAT2,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD,0 }, // 8
    D3DDECL_END()
};


struct BUMPVERTEX
{
	D3DXVECTOR3 vPosition;
	D3DXVECTOR3 vNormal;
	D3DXVECTOR3 vTangent;
	D3DXVECTOR3 vBinormal;
	D3DCOLOR color;
	TEXCOORD2 tex;

	BUMPVERTEX(){ memset(this, 0, sizeof(BUMPVERTEX)); color = 0xFFFFFFFF; }

	// TODO: proper FVF
	enum
	{
		FVF = ( D3DFVF_XYZ|D3DFVF_NORMAL|D3DFVF_DIFFUSE|D3DFVF_TEX1 )
	};

};

} // amorphous


#endif  /*  __FVF_BUMPVERTEX_H__  */
