#ifndef __FVF_NORMALVERTEX_H__
#define __FVF_NORMALVERTEX_H__


#include <d3d9.h>
#include <d3dx9.h>

#include "TextureCoord.hpp"


struct NORMALVERTEX
{
	D3DXVECTOR3 vPosition;

	D3DXVECTOR3 vNormal;

	D3DCOLOR color;

	TEXCOORD2 tex;


	enum eFVF
	{
		FVF = (D3DFVF_XYZ|D3DFVF_NORMAL|D3DFVF_DIFFUSE|D3DFVF_TEX1)
	};
};


#define D3DFVF_NORMALVERTEX (D3DFVF_XYZ | D3DFVF_NORMAL | D3DFVF_DIFFUSE | D3DFVF_TEX1)


const D3DVERTEXELEMENT9 NORMALVERTEX_DECLARATION[5] =
{
	{ 0, 0,  D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
	{ 0, 12, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL,   0 },
	{ 0, 24, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR,    0 },
	{ 0, 28, D3DDECLTYPE_FLOAT2,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_TEXCOORD, 0 },
	D3DDECL_END()
};


#endif	/* __FVF_NORMALVERTEX_H__ */
