#ifndef __FVFCOLORVERTEX_H__
#define __FVFCOLORVERTEX_H__

#include <d3d9.h>
#include <d3dx9.h>

struct COLORVERTEX
{
	D3DXVECTOR3 vPosition;

	D3DXVECTOR3 vNormal;

	D3DCOLOR color;

	enum eFVF
	{
		FVF = ( D3DFVF_XYZ | D3DFVF_NORMAL | D3DFVF_DIFFUSE )
	};

//	const static int m_i = 0;	// o.k.

//	const static int m_array[4] = { 0, 1, 2, 3 };	// error

//	const static int m_array[];	// o.k.  with the initialization outside the declaration

//	const static D3DVERTEXELEMENT9 DECLARATION [];

};

#define D3DFVF_COLORVERTEX ( D3DFVF_XYZ | D3DFVF_NORMAL | D3DFVF_DIFFUSE )

//const int COLORVERTEX::m_array[4] = { 0, 1, 2, 3 };

/*
const D3DVERTEXELEMENT9 COLORVERTEX::DECLARATION[4] =
{
	{ 0, 0,  D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
	{ 0, 12, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL,   0 },
	{ 0, 24, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR,    0 },
	D3DDECL_END()
};*/


const D3DVERTEXELEMENT9 COLORVERTEX_DECLARATION[4] =
{
	{ 0, 0,  D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_POSITION, 0 },
	{ 0, 12, D3DDECLTYPE_FLOAT3,   D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_NORMAL,   0 },
	{ 0, 24, D3DDECLTYPE_D3DCOLOR, D3DDECLMETHOD_DEFAULT, D3DDECLUSAGE_COLOR,    0 },
	D3DDECL_END()
};


#endif	/* __FVFCOLORVERTEX_H__ */
