#include "Stage/PlayerInfo.h"


void SetDefaultKeyBindFG()
{
	CKeyBind& kb = PLAYERINFO.KeyBind();

	kb.Assign( GIC_UP,			ACTION_MOV_PITCH_ACCEL_POS );
	kb.Assign( GIC_DOWN,		ACTION_MOV_PITCH_ACCEL_NEG );
	kb.Assign( GIC_LEFT,		ACTION_MOV_ROLL_ACCEL_POS );
	kb.Assign( GIC_RIGHT,		ACTION_MOV_ROLL_ACCEL_NEG );

	kb.Assign( GIC_NUMPAD8,		ACTION_MOV_PITCH_ACCEL_NEG );
	kb.Assign( GIC_NUMPAD5,		ACTION_MOV_PITCH_ACCEL_POS );
	kb.Assign( GIC_NUMPAD4,		ACTION_MOV_ROLL_ACCEL_POS );
	kb.Assign( GIC_NUMPAD6,		ACTION_MOV_ROLL_ACCEL_NEG );

	kb.Assign( GIC_NUMPAD0,		ACTION_MOV_BRAKE );
	kb.Assign( GIC_NUMPAD_ENTER,ACTION_MOV_BOOST );

//	kb.Assign( GIC_TAB,			ACTION_MISC_CYCLE_VIEWPOINTS );
	kb.Assign( 'Q',				ACTION_MISC_CYCLE_VIEWPOINTS );

	kb.Assign( GIC_ENTER,		ACTION_MISC_CYCLE_TARGET_FOCUS );

	kb.Assign( 'Z',				ACTION_ATK_FIRE );
	kb.Assign( 'X',				ACTION_ATK_FIRE1 );

	kb.Assign( GIC_SPACE,		ACTION_ATK_FIRE );
	kb.Assign( GIC_SPACE,		ACTION_ATK_FIRE1 );
//	kb.Assign( GIC_NOCONVERT,		 );
//	kb.Assign( GIC_BACK,		 );
//	kb.Assign( GIC_LSHIFT,		 );
	kb.Assign( 'N',		ACTION_MISC_TOGGLE_NIGHTVISION );
//	kb.Assign( 'C',		ACTION_MISC_TOGGLE_HEADLIGHT );
	kb.Assign( 'C',		ACTION_MISC_CYCLE_WEAPON );

	kb.Assign( 'A',		ACTION_ARMS_SELECTWEAPON1 );
	kb.Assign( 'T',		ACTION_ARMS_SELECTWEAPON2 );
	kb.Assign( 'G',		ACTION_ARMS_SELECTWEAPON3 );
	kb.Assign( 'V',		ACTION_ARMS_SELECTWEAPON4 );

	kb.Assign( GIC_MOUSE_BUTTON_L,	ACTION_ATK_FIRE );
//	kb.Assign( GIC_MOUSE_BUTTON_R,	ACTION_ATK_RAISEWEAPON );
	kb.Assign( GIC_MOUSE_BUTTON_R,	ACTION_ATK_UNLOCK_TRIGGER_SAFETY );
	kb.Assign( GIC_MOUSE_BUTTON_M,	ACTION_QMENU_OPEN );

//	kb.Assign( GIC_MOUSE_AXIS_X,	ACTION_MOV_ROLL_ACCEL_NEG );
//	kb.Assign( GIC_MOUSE_AXIS_Y,	ACTION_MOV_PITCH_ACCEL_NEG );

	kb.Assign( GIC_GPD_AXIS_X,		ACTION_MOV_ROLL_ACCEL_NEG );
	kb.Assign( GIC_GPD_AXIS_Y,		ACTION_MOV_PITCH_ACCEL_NEG );

	kb.Assign( GIC_GPD_AXIS_Z,		ACTION_MOV_LOOK_RIGHT );
	kb.Assign( GIC_GPD_ROTATION_Z,	ACTION_MOV_LOOK_UP );

	kb.Assign( GIC_GPD_BUTTON_00,	ACTION_MISC_CYCLE_TARGET_FOCUS );
	kb.Assign( GIC_GPD_BUTTON_09,	ACTION_MISC_CYCLE_WEAPON );
	kb.Assign( GIC_GPD_BUTTON_10,	ACTION_MISC_CYCLE_VIEWPOINTS );
	kb.Assign( GIC_GPD_BUTTON_11,	ACTION_MISC_CYCLE_VIEWPOINTS );

	kb.Assign( GIC_GPD_BUTTON_01,	ACTION_ATK_FIRE );
	kb.Assign( GIC_GPD_BUTTON_02,	ACTION_ATK_FIRE1 );
	kb.Assign( GIC_GPD_BUTTON_03,	ACTION_MISC_HOLD_RADAR );
	kb.Assign( GIC_GPD_BUTTON_04,	ACTION_MOV_YAW_ACCEL_NEG );
	kb.Assign( GIC_GPD_BUTTON_05,	ACTION_MOV_YAW_ACCEL_POS );

	kb.Assign( GIC_GPD_BUTTON_06,	ACTION_MOV_BRAKE );
	kb.Assign( GIC_GPD_BUTTON_07,	ACTION_MOV_BOOST );

	kb.Assign( GIC_MOUSE_WHEEL_UP,	ACTION_QMENU_UP );
	kb.Assign( GIC_MOUSE_WHEEL_DOWN,ACTION_QMENU_DOWN );

	kb.Assign( GIC_GPD_DOWN,        ACTION_MENU_OPEN_MENU_0 );
	kb.Assign( GIC_GPD_BUTTON_07,   ACTION_MENU_OK,                CKeyBind::ACTION_TYPE_SECONDARY );
	kb.Assign( GIC_GPD_BUTTON_06,   ACTION_MENU_CANCEL,            CKeyBind::ACTION_TYPE_SECONDARY );
	kb.Assign( GIC_GPD_UP,          ACTION_MENU_UP,                CKeyBind::ACTION_TYPE_SECONDARY );
	kb.Assign( GIC_GPD_DOWN,        ACTION_MENU_DOWN ,             CKeyBind::ACTION_TYPE_SECONDARY );
	kb.Assign( GIC_GPD_LEFT,        ACTION_MENU_NEXT_DIALOG_LEFT,  CKeyBind::ACTION_TYPE_SECONDARY );
	kb.Assign( GIC_GPD_RIGHT,       ACTION_MENU_NEXT_DIALOG_RIGHT, CKeyBind::ACTION_TYPE_SECONDARY );
}
